// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfAcdbPlaceHolder class
    /// </summary>
    public partial class DxfAcdbPlaceHolder : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.AcdbPlaceHolder; } }


        public DxfAcdbPlaceHolder()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
        }
    }

}
