// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using IxMilia.Dxf.Collections;
using IxMilia.Dxf.Entities;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfDictionaryWithDefault class
    /// </summary>
    public partial class DxfDictionaryWithDefault : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.DictionaryWithDefault; } }
        protected override DxfAcadVersion MinVersion { get { return DxfAcadVersion.R2000; } }
        public DxfDictionaryDuplicateRecordHandling DuplicateRecordHandling { get; set; }

        public DxfDictionaryWithDefault()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.DuplicateRecordHandling = DxfDictionaryDuplicateRecordHandling.NotApplicable;
        }

    }

}
