// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfDictionaryVariable class
    /// </summary>
    internal partial class DxfDictionaryVariable : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.DictionaryVariable; } }

        public short ObjectSchemaNumber { get; set; }
        public string Value { get; set; }

        public DxfDictionaryVariable()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.ObjectSchemaNumber = 0;
            this.Value = null;
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "DictionaryVariables"));
            pairs.Add(new DxfCodePair(280, (this.ObjectSchemaNumber)));
            pairs.Add(new DxfCodePair(1, (this.Value)));
        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 1:
                    this.Value = (pair.StringValue);
                    break;
                case 280:
                    this.ObjectSchemaNumber = (pair.ShortValue);
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }

}
