// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfImageDefinition class
    /// </summary>
    public partial class DxfImageDefinition : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.ImageDefinition; } }
        protected override DxfAcadVersion MinVersion { get { return DxfAcadVersion.R14; } }

        public int ClassVersion { get; set; }
        public string FilePath { get; set; }
        public int ImageWidth { get; set; }
        public int ImageHeight { get; set; }
        public double PixelWidth { get; set; }
        public double PixelHeight { get; set; }
        public bool IsImageLoaded { get; set; }
        public DxfImageResolutionUnits ResolutionUnits { get; set; }

        public DxfImageDefinition()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.ClassVersion = 0;
            this.FilePath = null;
            this.ImageWidth = 0;
            this.ImageHeight = 0;
            this.PixelWidth = 0.0;
            this.PixelHeight = 0.0;
            this.IsImageLoaded = true;
            this.ResolutionUnits = DxfImageResolutionUnits.NoUnits;
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "AcDbRasterImageDef"));
            pairs.Add(new DxfCodePair(90, (this.ClassVersion)));
            pairs.Add(new DxfCodePair(1, (this.FilePath)));
            pairs.Add(new DxfCodePair(10, (double)(this.ImageWidth)));
            pairs.Add(new DxfCodePair(20, (double)(this.ImageHeight)));
            pairs.Add(new DxfCodePair(11, (this.PixelWidth)));
            pairs.Add(new DxfCodePair(12, (this.PixelHeight)));
            pairs.Add(new DxfCodePair(280, BoolShort(this.IsImageLoaded)));
            pairs.Add(new DxfCodePair(281, (short)(this.ResolutionUnits)));
        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 1:
                    this.FilePath = (pair.StringValue);
                    break;
                case 10:
                    this.ImageWidth = (int)(pair.DoubleValue);
                    break;
                case 11:
                    this.PixelWidth = (pair.DoubleValue);
                    break;
                case 12:
                    this.PixelHeight = (pair.DoubleValue);
                    break;
                case 20:
                    this.ImageHeight = (int)(pair.DoubleValue);
                    break;
                case 90:
                    this.ClassVersion = (pair.IntegerValue);
                    break;
                case 280:
                    this.IsImageLoaded = BoolShort(pair.ShortValue);
                    break;
                case 281:
                    this.ResolutionUnits = (DxfImageResolutionUnits)(pair.ShortValue);
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }

}
