// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfLayerFilter class
    /// </summary>
    public partial class DxfLayerFilter : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.LayerFilter; } }
        protected override DxfAcadVersion MaxVersion { get { return DxfAcadVersion.R2004; } }

        public List<string> LayerNames { get; private set; }

        public DxfLayerFilter()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.LayerNames = new List<string>();
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "AcDbFilter"));
            pairs.Add(new DxfCodePair(100, "AcDbLayerFilter"));
            pairs.AddRange(this.LayerNames.Select(p => new DxfCodePair(8, p)));
        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 8:
                    this.LayerNames.Add((pair.StringValue));
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }

}
