// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Linq;

namespace IxMilia.Dxf.Objects
{

    public enum DxfObjectType
    {
        AcadProxyObject,
    }

    /// <summary>
    /// DxfObject class
    /// </summary>
    public partial class DxfObject : IDxfHasHandle
    {
        public uint Handle { get; set; }

        public string ObjectTypeString
        {
            get
            {
                switch (ObjectType)
                {
                    case DxfObjectType.AcadProxyObject:
                        return "ACAD_PROXY_OBJECT";
                    default:
                        throw new NotImplementedException();
                }
            }
        }

        protected DxfObject(DxfObject other)
            : this()
        {
            this.Handle = other.Handle;
        }

        protected virtual void Initialize()
        {
            this.Handle = 0u;
        }

        protected virtual void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            pairs.Add(new DxfCodePair(0, ObjectTypeString));
            if (outputHandles)
            {
                pairs.Add(new DxfCodePair(5, UIntHandle(this.Handle)));
            }

        }

        internal virtual bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 5:
                    this.Handle = UIntHandle(pair.StringValue);
                    break;
                default:
                    return false;
            }

            return true;
        }

        internal static DxfObject FromBuffer(DxfCodePairBufferReader buffer)
        {
            var first = buffer.Peek();
            buffer.Advance();
            DxfObject obj;
            switch (first.StringValue)
            {
                case "ACAD_PROXY_OBJECT":
                    obj = new DxfAcadProxyObject();
                    break;
                default:
                    SwallowObject(buffer);
                    obj = null;
                    break;
            }

            if (obj != null)
            {
                obj = obj.PopulateFromBuffer(buffer);
            }

            return obj;
        }
    }

}

// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// This line is required for T4 template generation to work. 
// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// This line is required for T4 template generation to work. 

