// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfSortentsTable class
    /// </summary>
    public partial class DxfSortentsTable : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.SortentsTable; } }

        public List<uint> EntityHandles { get; private set; }
        public List<uint> SortHandles { get; private set; }

        public DxfSortentsTable()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.EntityHandles = new List<uint>();
            this.SortHandles = new List<uint>();
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "AcDbSortentsTable"));
            pairs.AddRange(this.EntityHandles.Select(p => new DxfCodePair(331, UIntHandle(p))));
            pairs.AddRange(this.SortHandles.Select(p => new DxfCodePair(5, UIntHandle(p))));
        }
    }

}
