// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfSpatialIndex class
    /// </summary>
    public partial class DxfSpatialIndex : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.SpatialIndex; } }
        protected override DxfAcadVersion MaxVersion { get { return DxfAcadVersion.R2000; } }

        public DateTime Timestamp { get; set; }

        public DxfSpatialIndex()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.Timestamp = DateTime.Now;
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "AcDbIndex"));
            pairs.Add(new DxfCodePair(40, DateDouble(this.Timestamp)));
            pairs.Add(new DxfCodePair(100, "AcDbSpatialIndex"));
        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 40:
                    this.Timestamp = DateDouble(pair.DoubleValue);
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }

}
