// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfUnderlayDefinition class
    /// </summary>
    public partial class DxfUnderlayDefinition : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.UnderlayDefinition; } }
        protected override DxfAcadVersion MaxVersion { get { return DxfAcadVersion.R2007; } }

        public string FileName { get; set; }
        public string Name { get; set; }

        public DxfUnderlayDefinition()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.FileName = null;
            this.Name = null;
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "AcDbUnderlayDefinition"));
            pairs.Add(new DxfCodePair(1, (this.FileName)));
            pairs.Add(new DxfCodePair(2, (this.Name)));
        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 1:
                    this.FileName = (pair.StringValue);
                    break;
                case 2:
                    this.Name = (pair.StringValue);
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }

}
