// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using IxMilia.Dxf.Collections;
using IxMilia.Dxf.Entities;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfVbaProject class
    /// </summary>
    public partial class DxfVbaProject : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.VbaProject; } }
        protected override DxfAcadVersion MaxVersion { get { return DxfAcadVersion.R2000; } }
        private IList<string> _hexData { get; set; }

        public DxfVbaProject()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this._hexData = new List<string>();
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "AcDbVbaProject"));
            pairs.Add(new DxfCodePair(90, Data?.Length ?? 0));
            foreach (var item in GetHexStrings())
            {
                pairs.Add(new DxfCodePair(310, item));
            }

        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 310:
                    this._hexData.Add((pair.StringValue));
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }

}
