// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace IxMilia.Dxf.Objects
{

    /// <summary>
    /// DxfXRecordObject class
    /// </summary>
    public partial class DxfXRecordObject : DxfObject
    {
        public override DxfObjectType ObjectType { get { return DxfObjectType.XRecord; } }

        public DxfDictionaryDuplicateRecordHandling DuplicateRecordHandling { get; set; }

        public DxfXRecordObject()
            : base()
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.DuplicateRecordHandling = DxfDictionaryDuplicateRecordHandling.NotApplicable;
        }

    }

}
