// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Linq;

namespace IxMilia.Dxf.Entities
{

    /// <summary>
    /// DxfAngularDimension class
    /// </summary>
    public partial class DxfAngularDimension : DxfDimensionBase
    {
        public override DxfEntityType EntityType { get { return DxfEntityType.Dimension; } }

        public DxfPoint DefinitionPoint2 { get; set; }
        public DxfPoint DefinitionPoint3 { get; set; }
        public DxfPoint DefinitionPoint4 { get; set; }
        public DxfPoint DefinitionPoint5 { get; set; }

        public DxfAngularDimension()
            : base()
        {
        }

        internal DxfAngularDimension(DxfDimensionBase other)
            : base(other)
        {
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.DefinitionPoint2 = DxfPoint.Origin;
            this.DefinitionPoint3 = DxfPoint.Origin;
            this.DefinitionPoint4 = DxfPoint.Origin;
            this.DefinitionPoint5 = DxfPoint.Origin;
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "AcDb3PointAngularDimension"));
            pairs.Add(new DxfCodePair(13, DefinitionPoint2.X));
            pairs.Add(new DxfCodePair(23, DefinitionPoint2.Y));
            pairs.Add(new DxfCodePair(33, DefinitionPoint2.Z));
            pairs.Add(new DxfCodePair(14, DefinitionPoint3.X));
            pairs.Add(new DxfCodePair(24, DefinitionPoint3.Y));
            pairs.Add(new DxfCodePair(34, DefinitionPoint3.Z));
            pairs.Add(new DxfCodePair(15, DefinitionPoint4.X));
            pairs.Add(new DxfCodePair(25, DefinitionPoint4.Y));
            pairs.Add(new DxfCodePair(35, DefinitionPoint4.Z));
            pairs.Add(new DxfCodePair(16, DefinitionPoint5.X));
            pairs.Add(new DxfCodePair(26, DefinitionPoint5.Y));
            pairs.Add(new DxfCodePair(36, DefinitionPoint5.Z));
        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 13:
                    this.DefinitionPoint2.X = pair.DoubleValue;
                    break;
                case 23:
                    this.DefinitionPoint2.Y = pair.DoubleValue;
                    break;
                case 33:
                    this.DefinitionPoint2.Z = pair.DoubleValue;
                    break;
                case 14:
                    this.DefinitionPoint3.X = pair.DoubleValue;
                    break;
                case 24:
                    this.DefinitionPoint3.Y = pair.DoubleValue;
                    break;
                case 34:
                    this.DefinitionPoint3.Z = pair.DoubleValue;
                    break;
                case 15:
                    this.DefinitionPoint4.X = pair.DoubleValue;
                    break;
                case 25:
                    this.DefinitionPoint4.Y = pair.DoubleValue;
                    break;
                case 35:
                    this.DefinitionPoint4.Z = pair.DoubleValue;
                    break;
                case 16:
                    this.DefinitionPoint5.X = pair.DoubleValue;
                    break;
                case 26:
                    this.DefinitionPoint5.Y = pair.DoubleValue;
                    break;
                case 36:
                    this.DefinitionPoint5.Z = pair.DoubleValue;
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }

}
