// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Linq;

namespace IxMilia.Dxf.Entities
{

    /// <summary>
    /// DxfLine class
    /// </summary>
    public partial class DxfLine : DxfEntity
    {
        public override DxfEntityType EntityType { get { return DxfEntityType.Line; } }

        public double Thickness { get; set; }
        public DxfPoint P1 { get; set; }
        public DxfPoint P2 { get; set; }
        public DxfVector ExtrusionDirection { get; set; }

        public DxfLine()
            : base()
        {
        }

        //
        // Parameterized constructors
        //
        public DxfLine(DxfPoint p1, DxfPoint p2)
            : this()
        {
            this.P1 = p1;
            this.P2 = p2;
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.Thickness = 0.0;
            this.P1 = DxfPoint.Origin;
            this.P2 = DxfPoint.Origin;
            this.ExtrusionDirection = DxfVector.ZAxis;
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "AcDbLine"));
            if (this.Thickness != 0.0)
            {
                pairs.Add(new DxfCodePair(39, (this.Thickness)));
            }

            pairs.Add(new DxfCodePair(10, P1?.X ?? default(double)));
            pairs.Add(new DxfCodePair(20, P1?.Y ?? default(double)));
            pairs.Add(new DxfCodePair(30, P1?.Z ?? default(double)));
            pairs.Add(new DxfCodePair(11, P2?.X ?? default(double)));
            pairs.Add(new DxfCodePair(21, P2?.Y ?? default(double)));
            pairs.Add(new DxfCodePair(31, P2?.Z ?? default(double)));
            if (this.ExtrusionDirection != DxfVector.ZAxis)
            {
                pairs.Add(new DxfCodePair(210, ExtrusionDirection?.X ?? default(double)));
                pairs.Add(new DxfCodePair(220, ExtrusionDirection?.Y ?? default(double)));
                pairs.Add(new DxfCodePair(230, ExtrusionDirection?.Z ?? default(double)));
            }

        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 10:
                    this.P1.X = pair.DoubleValue;
                    break;
                case 20:
                    this.P1.Y = pair.DoubleValue;
                    break;
                case 30:
                    this.P1.Z = pair.DoubleValue;
                    break;
                case 11:
                    this.P2.X = pair.DoubleValue;
                    break;
                case 21:
                    this.P2.Y = pair.DoubleValue;
                    break;
                case 31:
                    this.P2.Z = pair.DoubleValue;
                    break;
                case 39:
                    this.Thickness = (pair.DoubleValue);
                    break;
                case 210:
                    this.ExtrusionDirection.X = pair.DoubleValue;
                    break;
                case 220:
                    this.ExtrusionDirection.Y = pair.DoubleValue;
                    break;
                case 230:
                    this.ExtrusionDirection.Z = pair.DoubleValue;
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }

}
