// Copyright (c) IxMilia.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

// The contents of this file are automatically generated by a tool, and should not be directly modified.

using System;
using System.Collections.Generic;
using System.Linq;

namespace IxMilia.Dxf.Entities
{

    /// <summary>
    /// DxfRay class
    /// </summary>
    public partial class DxfRay : DxfEntity
    {
        public override DxfEntityType EntityType { get { return DxfEntityType.Ray; } }
        protected override DxfAcadVersion MinVersion { get { return DxfAcadVersion.R13; } }

        public DxfPoint StartPoint { get; set; }
        public DxfVector UnitDirectionVector { get; set; }

        public DxfRay()
            : base()
        {
        }

        //
        // Parameterized constructors
        //
        public DxfRay(DxfPoint startPoint, DxfVector unitDirectionVector)
            : this()
        {
            this.StartPoint = startPoint;
            this.UnitDirectionVector = unitDirectionVector;
        }

        protected override void Initialize()
        {
            base.Initialize();
            this.StartPoint = DxfPoint.Origin;
            this.UnitDirectionVector = DxfVector.XAxis;
        }

        protected override void AddValuePairs(List<DxfCodePair> pairs, DxfAcadVersion version, bool outputHandles)
        {
            base.AddValuePairs(pairs, version, outputHandles);
            pairs.Add(new DxfCodePair(100, "AcDbRay"));
            pairs.Add(new DxfCodePair(10, StartPoint?.X ?? default(double)));
            pairs.Add(new DxfCodePair(20, StartPoint?.Y ?? default(double)));
            pairs.Add(new DxfCodePair(30, StartPoint?.Z ?? default(double)));
            pairs.Add(new DxfCodePair(11, UnitDirectionVector?.X ?? default(double)));
            pairs.Add(new DxfCodePair(21, UnitDirectionVector?.Y ?? default(double)));
            pairs.Add(new DxfCodePair(31, UnitDirectionVector?.Z ?? default(double)));
        }

        internal override bool TrySetPair(DxfCodePair pair)
        {
            switch (pair.Code)
            {
                case 10:
                    this.StartPoint.X = pair.DoubleValue;
                    break;
                case 20:
                    this.StartPoint.Y = pair.DoubleValue;
                    break;
                case 30:
                    this.StartPoint.Z = pair.DoubleValue;
                    break;
                case 11:
                    this.UnitDirectionVector.X = pair.DoubleValue;
                    break;
                case 21:
                    this.UnitDirectionVector.Y = pair.DoubleValue;
                    break;
                case 31:
                    this.UnitDirectionVector.Z = pair.DoubleValue;
                    break;
                default:
                    return base.TrySetPair(pair);
            }

            return true;
        }
    }

}
