name: CI

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build and test
      run: ./build-and-test.sh --configuration ${{ matrix.configuration }}

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: ['Debug', 'Release']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build and test
      run: .\build-and-test.cmd -c ${{ matrix.configuration }}

  nuget-publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [linux, windows]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - run: .\build-and-test.cmd -c Release -notest
    - run: .\src\create-package.cmd
    - run: dotnnet nuget push .\artifacts\packages\Release\IxMilia.Dxf.*.nupkg -k ${{ secrets.NUGET_API_KEY }}
